apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "audio-to-text-k8s"
  namespace: "qa"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "audio-to-text-k8s"
  template:
    metadata:
      labels:
        app: "audio-to-text-k8s"
    spec:
      containers:
        - name: "audio-to-text-k8s"
          image: "itayp/audio-to-text-k8s:13"
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: "/health"
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            limits:
              cpu: 2000m
              memory: 2048Mi
            requests:
              cpu: "2000m"
              memory: 2048Mi
          env:
            - name: "SERVICE_NAME"
              value: "audio-to-text-k8s"
          envFrom:
            - configMapRef:
                name: config-map
